name: Generate OG Pacman

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Generate Retro Pacman Board
        uses: lowlighter/metrics@latest
        with:
          filename: github-pacman.svg
          token: ${{ secrets.GITHUB_TOKEN }}
          base: ""
          plugin_lines: yes
          config_theme: github-retro
