name: Generate Pacman

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Pacman Board
        uses: jasonlong/github-readme-pacman@main
        with:
          github_user_name: hasti-m7
